name: cuidapet_api
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  args: ^2.4.2
  dotenv: ^4.1.0
  mysql1: ^0.20.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  get_it: ^7.6.4
  logger: ^1.4.0
  injectable: ^2.3.0
  jaguar_jwt: ^3.0.0
  http: ^0.13.6
  
dev_dependencies:
  pedantic: ^1.11.1
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  shelf_router_generator: ^1.1.0
  # shelf_router_generator: 
  #   git:
  #     url: https://github.com/google/dart-neats.git
  #     path: shelf_router_generator
  test: ^1.24.6
  mocktail: ^0.3.0

# dependency_overrides:
#   # Foi sobrescrito devido ao shelf_router_generator 
#   source_gen: ^1.0.0